name: clash_flt2_example
description: Demonstrates how to use the clash_flt2 plugin.
publish_to: "none"
version: 0.0.2+2

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get:
  path_provider:
  package_info_plus:
  network_tools: # get port occupying status
  yaml: # resolve port out of ClashFlt2 for using `network_tools`
  flutter_emoji: # fix `yaml` unsupported emoji problem

  clash_flt2:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
