name: clash_flt2
description: A new Flutter plugin project.
version: 0.0.1
homepage: https://github/com/LondonX/clash_flt2

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.1.0
  proxy_manager:

dev_dependencies:
  flutter_lints: ^2.0.0
  ffigen: ^9.0.1

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: ClashFlt2Plugin
      windows:
        pluginClass: ClashFlt2PluginCApi
      android:
        package: com.LondonX.clash_flt2
        pluginClass: ClashFlt2Plugin
      # ios:
      #   pluginClass: ClashFlt2Plugin
ffigen:
  output: "lib/ffi/generated_bindings.dart"
  headers:
    entry-points:
      - "fclash/dist/libclash.h"
